const dragonbones = dragonBones;
dragonbones.DragonBones = dragonbones.$DragonBones;
dragonbones.DragonBones.yDown = dragonbones.DragonBones.$yDown;
dragonbones.DragonBones.debug = dragonbones.DragonBones.$debug;
dragonbones.Point = dragonbones.$Point;
dragonbones.Point.prototype.clear = dragonbones.Point.prototype.$clear;
dragonbones.Rectangle = dragonbones.$Rectangle;
dragonbones.Rectangle.prototype.clear = dragonbones.Rectangle.prototype.$clear;
dragonbones.DragonBonesData = dragonbones.$DragonBonesData;
dragonbones.TextureAtlasData = dragonbones.$TextureAtlasData;
dragonbones.Armature = dragonbones.$Armature;
dragonbones.Armature.prototype.init = dragonbones.Armature.prototype.$init;
Object.defineProperty(dragonbones.Armature.prototype, "animation", Object.getOwnPropertyDescriptor(dragonbones.Armature.prototype, "animation"));
Object.defineProperty(dragonbones.Armature.prototype, "display", Object.getOwnPropertyDescriptor(dragonbones.Armature.prototype, "display"));
dragonbones.Bone = dragonbones.$Bone;
dragonbones.Bone.prototype.init = dragonbones.Bone.prototype.$init;
dragonbones.Bone.prototype.update = dragonbones.Bone.prototype.$update;
Object.defineProperty(dragonbones.Bone.prototype, "visible", Object.getOwnPropertyDescriptor(dragonbones.Bone.prototype, "visible"));
dragonbones.Animation = dragonbones.$Animation;
dragonbones.Animation.prototype.init = dragonbones.Animation.prototype.$init;
dragonbones.Animation.prototype.reset = dragonbones.Animation.prototype.$reset;
dragonbones.Animation.prototype.play = dragonbones.Animation.prototype.$play;
dragonbones.Animation.prototype.fadeIn = dragonbones.Animation.prototype.$fadeIn;
dragonbones.BaseFactory = dragonbones.$BaseFactory;
dragonbones.BaseFactory.prototype.parseDragonBonesData = dragonbones.BaseFactory.prototype.$parseDragonBonesData;
dragonbones.BaseFactory.prototype.parseTextureAtlasData = dragonbones.BaseFactory.prototype.$parseTextureAtlasData;
dragonbones.BaseFactory.prototype.clear = dragonbones.BaseFactory.prototype.$clear;
dragonbones.BaseFactory.prototype.buildArmature = dragonbones.BaseFactory.prototype.$buildArmature;
Object.defineProperty(dragonbones.BaseFactory.prototype, "dragonBones", Object.getOwnPropertyDescriptor(dragonbones.BaseFactory.prototype, "dragonBones"));
dragonbones.PixiFactory = dragonbones.$PixiFactory;
dragonbones.PixiFactory.prototype.buildArmatureDisplay = dragonbones.PixiFactory.prototype.$buildArmatureDisplay;
Object.defineProperty(dragonbones.PixiFactory, "factory", Object.getOwnPropertyDescriptor(dragonbones.PixiFactory, "factory"));
module.exports = dragonbones;